language: cpp

compiler:
  - gcc

sudo: true

before_install:
  - sudo apt-get install libboost-all-dev libfreeimage-dev
  - git clone https://github.com/lronaldo/cpctelera.git
  - cd cpctelera
  - chmod +x setup.sh
  - ./setup.sh
  - cd ..

script:
  - make

os:
  - linux
