language: cpp

compiler:
  - gcc

sudo: true

before_install:
  - gcc --version
  - g++ --version
  - sudo apt-get install libboost-all-dev libfreeimage-dev gcc g++
  - git clone https://github.com/lronaldo/cpctelera.git
  - cd cpctelera
  - git checkout tags/v1.2.3
  - chmod +x setup.sh
  - sudo ./setup.sh
  - cd ..
  - cat /home/travis/build/aalmiramolla/CPCRetroDev-2015/cpctelera/cpctelera/logs/tool_building.log

script:
  - make

os:
  - linux
