language: cpp

compiler:
  - gcc

sudo: true

env:
  global:
    - GCC_VERSION="4.8"

before_install:
  - sudo apt-get install libboost-all-dev libfreeimage-dev
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - git clone https://github.com/lronaldo/cpctelera.git
  
install:
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq "g++-${GCC_VERSION}"; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-${GCC_VERSION}" CC="gcc-${GCC_VERSION}"; fi
  - cd cpctelera
  - sed -i s/g++/g++-4.8/g cpctelera/tools/img2cpc/Makefile.others
  - chmod +x setup.sh
  - sudo ./setup.sh
  - cd ..
  - cat /home/travis/build/aalmiramolla/CPCRetroDev-2015/cpctelera/cpctelera/logs/tool_building.log

script:
  - make

os:
  - linux
