language: cpp

compiler:
  - gcc

before_install:
  - git clone https://github.com/lronaldo/cpctelera.git
  - cd cpctelera
  - chmod +x setup.sh
  - ./setup.sh
  - cd ..

script:
  - make

os:
  - linux
