language: cpp

compiler:
  - gcc

sudo: true

env:
  global:
    - GCC_VERSION="4.8"

before_install:
  - sudo apt-get install libboost-all-dev libfreeimage-dev
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - git clone https://github.com/lronaldo/cpctelera.git

install:
  - sudo apt-get install -qq "g++-${GCC_VERSION}"
  - cd cpctelera
  - sed -i s/g++/g++-4.8/g cpctelera/tools/img2cpc/Makefile.others
  - chmod +x setup.sh
  - "./setup.sh"
  - cat home/travis/build/CalivGames/CPCRetroDev-2015/cpctelera/cpctelera/logs/tool_building.log
  - cd ..
  - sed -i '/[ -z "$PS1" ] && return/d' ~/.bashrc
  - source ~/.bashrc

script:
  - make

os:
  - linux

deploy:
  provider: releases
  api_key:
    secure: FT9Sj2rmrWnh3OC6JQlM89Ra8giYravHK78zJBMqF7Oco3y1vE1GyZyzPbrf5nkmc+Vhghq28hTb5gp0Dgl4aAe0vfgGzHI8ikuTCvUrRIXq8l6EbgHSAUW6XdgV0htezAFKMxU3Zc2+CuBcjSIM1FN2ha5FhX+0+duEsPP2N6kmkUOVJcbGqmALsCE9ZrqbKJIHFr5sfVgEPiGvHMn6P54KcmNUARsBp/5qK3pXS5ng7NzFjHeYl1VnFHW9Hkqpfruevyy17gMH4PzfROt4A5xkA6vt/1fvZNFEK9bWK+NK2jTi7tmgjGvfUjQpLZ3P59w2Z8ceRerWykXhOm+FtA6T71OS0ZoUxrXUEnwFAvcqbuRZHAd1GzgMLaGV7y6ycdrIZJ8bJ/UgoxNzLWgIvYW+9N1Su7jeZaDmMTVCv9jME2j3iNK5kfSuDV0fL+yHhrdlHkOsJ+V1NUkFs86KZdUVR9U8WncdqOJDOBrQjWrNHv0EVicvnk/uQ+wKH58IBnYCRsGP+mfWm50TRyHry1rD9DTDMu33Tf3ltk7Ty6225HrCvQqHgsD5fg/tazVnz7oxhyYoi/pb8c/UdSqHi/rTPU/wZCuTmcNqKA2jp7ovbKmchyBAEfkOoxY3Oi8+SqE1zMT7RcetXvoCvyyq+JaNrMCZQUJH7IFx4rhBOJ0=
  file:
    - "CPCRetroDevGame.dsk"
    - "CPCRetroDevGame.cdt"
  on:
    repo: CalivGames/CPCRetroDev-2015
    tags: true
    branch: master