language: cpp

compiler:
  - gcc

sudo: true

env:
  global:
    - GCC_VERSION="4.8"

before_install:
  - sudo apt-get install libboost-all-dev libfreeimage-dev
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - git clone https://github.com/lronaldo/cpctelera.git
  
install:
  - sudo apt-get install -qq "g++-${GCC_VERSION}"
  - cd cpctelera
  - sed -i s/g++/g++-4.8/g cpctelera/tools/img2cpc/Makefile.others
  - chmod +x setup.sh
  - ./setup.sh
  - cd ..
  - source ~/.bashrc

script:
  - make

os:
  - linux
