language: cpp

compiler:
  - gcc

sudo: true

before_install:
  - sudo apt-get install libboost-all-dev libfreeimage-dev
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - sudo apt-get install -qq g++-4.8
  - export CXX="g++-4.8"
  - git clone https://github.com/lronaldo/cpctelera.git
  - cd cpctelera
  - git checkout tags/v1.2.3
  - chmod +x setup.sh
  - echo $CXX
  - sudo ./setup.sh
  - echo $CXX
  - cd ..
  - cat /home/travis/build/aalmiramolla/CPCRetroDev-2015/cpctelera/cpctelera/logs/tool_building.log

script:
  - make

os:
  - linux
